### ISSUE TITLE
Fix duplicate key error

### ISSUE THREAD

**Issue by bartolomej** [onflowser/flowser#62]
Investigate why duplicate error occurs on project startup. Example logs:

```
backend     | [Flowser] block save error:  BulkWriteError: E11000 duplicate key error collection: flowser.blocks index: IDX_8244fa1495c4e9222a01059244 dup key: { id: "b89a9248a2ae223463068847b6c62b69e035003511d180a3caea3cae8a3d3462" }
backend     |     at OrderedBulkOperation.handleWriteError (/app/node_modules/mongodb/lib/bulk/common.js:1355:9)
backend     |     at resultHandler (/app/node_modules/mongodb/lib/bulk/common.js:579:23)
backend     |     at /app/node_modules/mongodb/lib/core/connection/pool.js:407:18
backend     |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
backend     |   driver: true,
backend     |   code: 11000,
backend     |   writeErrors: [ WriteError { err: [Object] } ],
backend     |   result: BulkWriteResult {
backend     |     result: {
backend     |       ok: 1,
backend     |       writeErrors: [Array],
backend     |       writeConcernErrors: [],
backend     |       insertedIds: [Array],
backend     |       nInserted: 0,
backend     |       nUpserted: 0,
backend     |       nMatched: 0,
backend     |       nModified: 0,
backend     |       nRemoved: 0,
backend     |       upserted: []
backend     |     },
backend     |     [Symbol(upsertedIds)]: undefined,
backend     |     [Symbol(insertedIds)]: undefined
backend     |   }
backend     | }
```

**Comment by bartolomej** [comment]
The issue was that we defined event id as `transactionId:eventType` instead of `transactionId:eventType:eventIndex`.
