### ISSUE TITLE
Unable to Launch Flowser 

### ISSUE THREAD

**Issue by AliSMAmin** [onflowser/flowser#87]
**Describe the bug**

Failed at the flowser@1.0.0 dev:logs script 'docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml logs -f'.

**To Reproduce**

Installed Flowser and all dependencies as per documentation.` npm run dev:start` from root directory leads to Docker compose issue.

**Expected behavior**

Flowser instatiates.

**Desktop (please complete the following information):**
 - Linux Mint 
 - Chrome

**Log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev:logs' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'predev:logs', 'dev:logs', 'postdev:logs' ]
5 info lifecycle flowser@1.0.0~predev:logs: flowser@1.0.0
6 silly lifecycle flowser@1.0.0~predev:logs: no script for predev:logs, continuing
7 info lifecycle flowser@1.0.0~dev:logs: flowser@1.0.0
8 verbose lifecycle flowser@1.0.0~dev:logs: unsafe-perm in lifecycle true
9 verbose lifecycle flowser@1.0.0~dev:logs: PATH: /usr/share/npm/bin/node-gyp-bin:/home/abulut/flowser/node_modules/.bin:/home/abulut/Downloads/GoLand-2021.3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle flowser@1.0.0~dev:logs: CWD: /home/abulut/flowser
11 silly lifecycle flowser@1.0.0~dev:logs: Args: [ '-c',
11 silly lifecycle   'docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml logs -f' ]
12 silly lifecycle flowser@1.0.0~dev:logs: Returned: code: 1  signal: null
13 info lifecycle flowser@1.0.0~dev:logs: Failed to exec dev:logs script
14 verbose stack Error: flowser@1.0.0 dev:logs: `docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml logs -f`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid flowser@1.0.0
16 verbose cwd /home/abulut/flowser
17 error Linux 5.4.0-110-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dev:logs"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error flowser@1.0.0 dev:logs: `docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml logs -f`
22 error Exit status 1
23 error Failed at the flowser@1.0.0 dev:logs script 'docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml logs -f'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the flowser package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml logs -f
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs flowser
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls flowser
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by bartolomej** [comment]
Hey @AliSMAmin, thanks for reporting this issue!

The log that you provided is an output of`npm run dev:logs`, correct ? Can you also provide the output you receive after running the `npm run dev:start` command itself ?

Also just a note, the prefered command for running Flowser app for non-development purpouses is `npm run prod:start`

**Comment by AliSMAmin** [comment]
Hey @bartolomej, here is the output for `npm run dev:start`

```
npm ERR! Linux 5.4.0-110-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev:start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! flowser@1.0.0 dev:start: `docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml up -d`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flowser@1.0.0 dev:start script 'docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml up -d'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flowser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml up -d
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flowser
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flowser
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/abulut/flowser/npm-debug.log
```

**Comment by AliSMAmin** [comment]
npm run prod:start

```
> flowser@1.0.0 prod:start /home/abulut/flowser
> docker-compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml up -d

Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE             Specify an alternate compose file (default: docker-compose.yml)
  -p, --project-name NAME     Specify an alternate project name (default: directory name)
  --verbose                   Show more output
  --no-ansi                   Do not print ANSI control characters
  -v, --version               Print version and exit
  -H, --host HOST             Daemon socket to connect to

  --tls                       Use TLS; implied by --tlsverify
  --tlscacert CA_PATH         Trust certs signed only by this CA
  --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
  --tlskey TLS_KEY_PATH       Path to TLS key file
  --tlsverify                 Use TLS and verify the remote
  --skip-hostname-check       Don't check the daemon's hostname against the name specified
                              in the client certificate (for example if your docker host
                              is an IP address)
  --project-directory PATH    Specify an alternate working directory
                              (default: the path of the Compose file)

Commands:
  build              Build or rebuild services
  bundle             Generate a Docker bundle from the Compose file
  config             Validate and view the Compose file
  create             Create services
  down               Stop and remove containers, networks, images, and volumes
  events             Receive real time events from containers
  exec               Execute a command in a running container
  help               Get help on a command
  images             List images
  kill               Kill containers
  logs               View output from containers
  pause              Pause services
  port               Print the public port for a port binding
  ps                 List containers
  pull               Pull service images
  push               Push service images
  restart            Restart services
  rm                 Remove stopped containers
  run                Run a one-off command
  scale              Set number of containers for a service
  start              Start services
  stop               Stop services
  top                Display the running processes
  unpause            Unpause services
  up                 Create and start containers
  version            Show the Docker-Compose version information

npm ERR! Linux 5.4.0-110-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "prod:start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! flowser@1.0.0 prod:start: `docker-compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml up -d`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flowser@1.0.0 prod:start script 'docker-compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml up -d'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flowser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     docker-compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml up -d
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flowser
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flowser
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/abulut/flowser/npm-debug.log
```

**Comment by bartolomej** [comment]
Hey @AliSMAmin! Sorry for not responding earlier, but we've been very busy with our upcomming release of flowser desktop app.

This change should also fix the issue that you had here, so maybe follow us on Twitter for live updates: https://twitter.com/onflowser
